#!/bin/bash
#Wrapper for games

if ((EUID == 0)); then
  echo "Do not run as root"
  exit 1
fi

# Days 6 and 7 are weekends in bash as 1 is Monday
if test -f /opt/ci_time_saver
then
	DOW=$(date +%u)
	if [ $DOW != 6 ] && [ $DOW != 7 ]
	then
		echo "Games while fun...you really only have time for this on weekends"
		exit 1
	fi
fi

mapfile -t application_directories < "/opt/quick_ci_launcher"

if test -z $1
	then
	for directory in "${application_directories[@]}"; do
		key=${directory%=*}
        	value=${directory#*=}
		cd /opt
		echo $value
		ls -1 --color $key
	done
exit 0
fi

cd /opt
GAME_EXEC=$(find . -name $1)
eval $GAME_EXEC
